stages:
  - build

.build:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  stage: build
  script:
    - ./gradlew --warning-mode=all build
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
    - key: $CI_COMMIT_REF_SLUG
      fallback_keys:
        - master-protected
      paths:
        - .gradle/caches
#   artifacts:
#     when: always
#     paths:
#       - build/test-results/
#       - build/reports/jacoco/
#     reports:
#       junit: build/test-results/**/TEST-*.xml
#       coverage_report:
#         coverage_format: jacoco
#         path: build/reports/jacoco/**/*.xml

build:java8:
  extends: .build
  image: eclipse-temurin:8-jdk

build:java11:
  extends: .build
  image: eclipse-temurin:11.0.29_7-jdk

build:java17:
  extends: .build
  image: eclipse-temurin:17.0.17_10-jdk

build:java21:
  extends: .build
  image: eclipse-temurin:21.0.9_10-jdk

build:java24:
  extends: .build
  image: eclipse-temurin:24-jdk
