stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.build:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  stage: build
  script:
    - ./gradlew --build-cache --warning-mode=all build
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
    - key: "${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME_SLUG}"
      fallback_keys:
        - "${CI_DEFAULT_BRANCH_SLUG}_${CI_JOB_NAME_SLUG}"
      paths:
        - .gradle/caches
#   artifacts:
#     when: always
#     paths:
#       - build/test-results/
#       - build/reports/jacoco/
#     reports:
#       junit: build/test-results/**/TEST-*.xml
#       coverage_report:
#         coverage_format: jacoco
#         path: build/reports/jacoco/**/*.xml

build:java8:
  extends: .build
  image: eclipse-temurin:8-jdk@sha256:fb1461dc88df08276706709d388f71c9e5eb2dc979e0ce9131118d9b601db331
  allow_failure: true

build:java11:
  extends: .build
  image: eclipse-temurin:11.0.31_11-jdk@sha256:1d5e03cb02c10e21884f2ceae93e6d91c3d8474113e4912fb21b6b1f7330e781
  allow_failure: true

build:java17:
  extends: .build
  image: eclipse-temurin:17.0.19_10-jdk@sha256:b04a8c5d46e210873ffd1af6ad5f4d62c69ed3a6736993556eae60bba1373a23

build:java21:
  extends: .build
  image: eclipse-temurin:21.0.11_10-jdk@sha256:b9142586f9712700c6c9e07adcedfb18608b1a3a056e4001423a3354adfa9d80

build:java25:
  extends: .build
  image: eclipse-temurin:25.0.3_9-jdk@sha256:c2b7ea21649875fb9052237ac4e3cd4ef63968a2a389a0a1b1a72a5e53e5c93f
  allow_failure: true
