stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.build:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  stage: build
  script:
    - ./gradlew --build-cache --warning-mode=all build
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
    - key: "${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME_SLUG}"
      fallback_keys:
        - "${CI_DEFAULT_BRANCH_SLUG}_${CI_JOB_NAME_SLUG}"
      paths:
        - .gradle/caches
#   artifacts:
#     when: always
#     paths:
#       - build/test-results/
#       - build/reports/jacoco/
#     reports:
#       junit: build/test-results/**/TEST-*.xml
#       coverage_report:
#         coverage_format: jacoco
#         path: build/reports/jacoco/**/*.xml

build:java8:
  extends: .build
  image: eclipse-temurin:8-jdk@sha256:1c53219c9cc1ad35a5285694756b591801a26fef036da845d1f71680dcfdec90
  allow_failure: true

build:java11:
  extends: .build
  image: eclipse-temurin:11.0.30_7-jdk@sha256:c209d7d4b04578d9f420f54865ba6b3c94904b3bce8b4131a6db20ebe15439b0
  allow_failure: true

build:java17:
  extends: .build
  image: eclipse-temurin:17.0.18_8-jdk@sha256:2cffc61cde3d5bd27a764c87508eb7714856fe396ab56a0f37e180a9e876bca2

build:java21:
  extends: .build
  image: eclipse-temurin:21.0.10_7-jdk@sha256:3b0a98dfbdf1067c20a7854cec159551777d2ee1381bc76cd4bd0719f543b148

build:java25:
  extends: .build
  image: eclipse-temurin:25.0.2_10-jdk@sha256:bee2e23ab444ed60daf8123e36478bc4a286ba7835bec6f9daf9eba1d50a86a2
  allow_failure: true
